using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace RestaurantAppClient.Common.Helpers
{
    // Generated by IconFont2Code: https://andreinitescu.github.io/IconFont2Code
    // If you change the class to 'public' in order to use it outside its assembly
    //  you should also change the fields from 'const' to 'public static readonly'
    static class IconFont
    {
        public const string Silverware = "\ue900";
        public const string FileText = "\ue901";
        public const string Cart = "\ue902";
        public const string User = "\ue903";
        public const string Settings = "\ue904";
        public const string Menu = "\ue905";
        public const string Cross = "\ue906";
    }
}
